import React, { PureComponent } from 'react';

export default class Guide extends PureComponent {
  render() {
    return (
      <>
        <div className="container mt-5">
          <div className="text-center">
            <h2 className="display-4 mb-5">Quick Guide</h2>
          </div>
          <div className="row">
            <div className="col-md-4 mb-4">
              <div className="card h-100 border-0 shadow">
                <img src="6343825.jpg" className="card-img-top" alt="Username and Password" />
                <div className="card-body">
                  <h5 className="card-title">Username and Password Entered</h5>
                  <p className="card-text">Users initiate their login by entering a username and password. This step employs secure hashing to compare the provided credentials against stored data, ensuring the first layer of authentication is robust and secure against unauthorized access attempts.</p>
                </div>
              </div>
            </div>
            <div className="col-md-4 mb-4">
              <div className="card h-100 border-0 shadow">
                <img src="5243321.jpg" className="card-img-top" alt="Verification via Secondary Factor" />
                <div className="card-body">
                  <h5 className="card-title">Verification via Secondary Factor</h5>
                  <p className="card-text">Upon successful primary authentication, users are prompted for a second factor, typically an OTP sent via email or generated by an Authenticator App. This step adds an additional layer of security, significantly reducing the risk of unauthorized access even if the primary credentials are compromised.</p>
                </div>
              </div>
            </div>
            <div className="col-md-4 mb-4">
              <div className="card h-100 border-0 shadow">
                <img src="Wavy_Bus-24_Single-11.jpg" className="card-img-top" alt="User Access Granted" />
                <div className="card-body">
                  <h5 className="card-title">User Access Granted</h5>
                  <p className="card-text">Once the secondary verification is successfully completed, users gain access to a Digital Repository. This Repository's content and available resources are tailored based on the user’s role and permissions, ensuring a secure, customized user experience that adheres to the principle of least privilege.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </>
    );
  }
}
